apiVersion: batch/v1
kind: Job
metadata:
  name: restart-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceded
spec:
  template:
    spec:
      serviceAccountName: pod-delete-sa
      containers:
      - name: restart
        image: vvaarruunn/kubectlrestart:v1
        command: ["bash", "restart.sh"]
      restartPolicy: Never
  backoffLimit: 0
